import type { Diagnostic } from './types.ts';

export interface CodeownersEditOptions {
  readonly filePath: string;
  readonly sourceText: string;
  readonly generatedHeaderMatch?: string;
}

const DEFAULT_HEADER = 'This file is generated by @strays/build';

export function validateCodeownersEdit(options: CodeownersEditOptions): Diagnostic[] {
  if (!options.filePath.endsWith('CODEOWNERS')) return [];

  const headerMatch = options.generatedHeaderMatch ?? DEFAULT_HEADER;
  if (options.sourceText.includes(headerMatch)) return [];

  return [
    {
      ruleId: 'no-codeowners-edit',
      severity: 'error',
      message:
        'CODEOWNERS appears to be hand-edited. It is generated from strays.config.ts by `strays generate`. Restore the generated file.',
      line: 1,
      column: 1,
    },
  ];
}
