import { describe, expect, it } from 'bun:test';
import { validateCodeownersEdit } from './validateCodeownersEdit.ts';

describe('validateCodeownersEdit', () => {
  it('passes when the file has the generated header', () => {
    const result = validateCodeownersEdit({
      filePath: '.github/CODEOWNERS',
      sourceText: '# This file is generated by @ownheim/build. Do not edit by hand.\n* @org/billing\n',
    });
    expect(result).toEqual([]);
  });

  it('flags hand-edited CODEOWNERS', () => {
    const result = validateCodeownersEdit({
      filePath: '.github/CODEOWNERS',
      sourceText: '# Hand-rolled\n* @org/billing\n',
    });
    expect(result).toHaveLength(1);
    expect(result[0]?.ruleId).toBe('no-codeowners-edit');
  });

  it('only fires for CODEOWNERS files', () => {
    const result = validateCodeownersEdit({
      filePath: 'packages/billing/charge.ts',
      sourceText: '# definitely not codeowners\n',
    });
    expect(result).toEqual([]);
  });

  it('honours a custom header marker', () => {
    const result = validateCodeownersEdit({
      filePath: '.github/CODEOWNERS',
      sourceText: '# Generated by ours\n* @org/billing\n',
      generatedHeaderMatch: 'Generated by ours',
    });
    expect(result).toEqual([]);
  });
});
