import { describe, expect, it } from 'bun:test';
import { defineStrays } from '@strays/core/defineStrays';
import type { Owner, StraysConfig } from '@strays/core/types';
import { plugin as oxlintPlugin } from './plugin.ts';
import type { OxlintRuleContext } from './rules/no-strays.ts';

const config = defineStrays({
  owners: {
    Billing: { id: 'Billing', github: '@org/billing' },
    Platform: { id: 'Platform', github: '@org/platform' },
  },
  rules: [
    { glob: 'packages/billing/**', owner: 'Billing' },
    { glob: '**', owner: 'Platform', fallback: true },
  ],
}) as unknown as StraysConfig<Record<string, Owner>>;

describe('oxlint plugin', () => {
  it('exposes both rules under the @strays prefix', () => {
    expect(oxlintPlugin.rules['no-strays']).toBeDefined();
    expect(oxlintPlugin.rules['no-codeowners-edit']).toBeDefined();
  });

  it('no-strays reports a diagnostic for fallback-only files', () => {
    const reports: Array<{ message: string }> = [];
    const ctx: OxlintRuleContext = {
      filename: 'tools/deploy.ts',
      sourceText: 'export const x = 1;\n',
      options: [{ config }],
      report: (r) => reports.push({ message: r.message }),
    };

    oxlintPlugin.rules['no-strays'].create(ctx).Program();
    expect(reports).toHaveLength(1);
    expect(reports[0]?.message).toContain('fallback');
  });

  it('no-strays does not report when a rule matches', () => {
    const reports: Array<{ message: string }> = [];
    const ctx: OxlintRuleContext = {
      filename: 'packages/billing/charge.ts',
      sourceText: 'export const x = 1;\n',
      options: [{ config }],
      report: (r) => reports.push({ message: r.message }),
    };

    oxlintPlugin.rules['no-strays'].create(ctx).Program();
    expect(reports).toEqual([]);
  });

  it('no-codeowners-edit fires only on hand-edited CODEOWNERS', () => {
    const handEdited: Array<{ message: string }> = [];
    const generated: Array<{ message: string }> = [];

    oxlintPlugin.rules['no-codeowners-edit']
      .create({
        filename: '.github/CODEOWNERS',
        sourceText: '* @org/billing\n',
        options: [],
        report: (r) => handEdited.push({ message: r.message }),
      })
      .Program();

    oxlintPlugin.rules['no-codeowners-edit']
      .create({
        filename: '.github/CODEOWNERS',
        sourceText: '# This file is generated by @strays/build\n* @org/billing\n',
        options: [],
        report: (r) => generated.push({ message: r.message }),
      })
      .Program();

    expect(handEdited).toHaveLength(1);
    expect(generated).toEqual([]);
  });
});
